/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description The process is up. Deliberately checks nothing else, so a database outage does not
         *     cause the orchestrator to restart healthy API containers.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Ready to serve traffic: database reachable and schema at the expected migration.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_api_v1_auth_github_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_auth_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{login}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_orgs__login__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{login}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repositories */
        get: operations["repositories_api_v1_orgs__login__repositories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{login}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Findings */
        get: operations["findings_api_v1_orgs__login__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{login}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity */
        get: operations["activity_api_v1_orgs__login__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{login}/vex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vex Documents */
        get: operations["vex_documents_api_v1_orgs__login__vex_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{login}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_api_v1_orgs__login__policy_get"];
        /** Put Policy */
        put: operations["put_policy_api_v1_orgs__login__policy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{login}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_orgs__login__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repository */
        get: operations["repository_api_v1_repositories__repository_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scans */
        get: operations["scans_api_v1_repositories__repository_id__scans_get"];
        put?: never;
        /** Rescan */
        post: operations["rescan_api_v1_repositories__repository_id__scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/pull-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull Requests */
        get: operations["pull_requests_api_v1_repositories__repository_id__pull_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/vex/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vex Preview
         * @description The document as it would be generated now. Nothing is stored. Available to every viewer,
         *     including demo visitors.
         */
        get: operations["vex_preview_api_v1_repositories__repository_id__vex_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/vex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Vex */
        post: operations["create_vex_api_v1_repositories__repository_id__vex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Detail */
        get: operations["scan_detail_api_v1_scans__scan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Events
         * @description Live scan progress. Each event is a read of the scan row — the pipeline's own record —
         *     so the stream can never show progress that did not happen.
         */
        get: operations["scan_events_api_v1_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/sbom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sbom */
        get: operations["sbom_api_v1_scans__scan_id__sbom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Finding */
        get: operations["get_finding_api_v1_findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_v1_findings__finding_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo */
        get: operations["demo_api_v1_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Demo Scan */
        post: operations["run_demo_scan_api_v1_demo_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisories/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Advisory Health
         * @description Freshness of each intelligence source. Stale data is reported, never hidden: a scan against
         *     week-old advisories should say so.
         */
        get: operations["advisory_health_api_v1_advisories_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vex/{document_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Vex */
        get: operations["download_vex_api_v1_vex__document_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Github Webhook */
        post: operations["github_webhook_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIExtractionOut */
        AIExtractionOut: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latency Ms */
            latency_ms: number | null;
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
        };
        /** AdvisoryOut */
        AdvisoryOut: {
            /** Id */
            id: string;
            /** Aliases */
            aliases: string[];
            /** Summary */
            summary: string | null;
            /** Details */
            details: string | null;
            severity: components["schemas"]["Severity"];
            /** Cvss Vector */
            cvss_vector: string | null;
            /** Cvss Score */
            cvss_score: string | null;
            /** References */
            references: {
                [key: string]: string;
            }[];
            /** Published At */
            published_at: string | null;
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** Url */
            url: string;
        };
        /** AnalysisOut */
        AnalysisOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            verdict: components["schemas"]["Verdict"];
            confidence: components["schemas"]["Confidence"];
            /** Reasons */
            reasons: {
                [key: string]: unknown;
            }[];
            /** Symbols */
            symbols: {
                [key: string]: unknown;
            }[];
            /** Analyzer Version */
            analyzer_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Scan Id
             * Format: uuid
             */
            scan_id: string;
            /** Paths */
            paths: components["schemas"]["PathOut"][];
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Seq */
            seq: number;
            /** Action */
            action: string;
            /** Actor Type */
            actor_type: string;
            /** Actor Login */
            actor_login: string | null;
            /** Target Type */
            target_type: string | null;
            /** Target Id */
            target_id: string | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Correlation Id */
            correlation_id: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /** DemoOut */
        DemoOut: {
            /** Organization Login */
            organization_login: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            latest_scan: components["schemas"]["ScanOut"] | null;
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            };
            /** Symbol Provenance */
            symbol_provenance: string;
            /** Ai Enabled */
            ai_enabled: boolean;
        };
        /** DemoScanOut */
        DemoScanOut: {
            scan: components["schemas"]["ScanOut"];
            /** Created */
            created: boolean;
        };
        /** ExploitationOut */
        ExploitationOut: {
            /** Kev */
            kev: {
                [key: string]: unknown;
            } | null;
            /** Epss */
            epss: {
                [key: string]: unknown;
            } | null;
        };
        /** FindingDetailOut */
        FindingDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Advisory Id */
            advisory_id: string;
            /** Aliases */
            aliases: string[];
            /** Summary */
            summary: string | null;
            /** Package */
            package: string;
            /** Installed Version */
            installed_version: string | null;
            severity: components["schemas"]["Severity"];
            /** Cvss Score */
            cvss_score: string | null;
            verdict: components["schemas"]["Verdict"] | null;
            effective_verdict: components["schemas"]["Verdict"] | null;
            confidence: components["schemas"]["Confidence"] | null;
            review_state: components["schemas"]["ReviewState"];
            /** Risk Score */
            risk_score: string | null;
            /** Kev */
            kev: boolean;
            /** Epss Percentile */
            epss_percentile: string | null;
            presence: components["schemas"]["Presence"];
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Repository Full Name */
            repository_full_name: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Version */
            version: number;
            /** Analysis State */
            analysis_state: string;
            decided_verdict: components["schemas"]["Verdict"] | null;
            vex_status: components["schemas"]["VexStatus"] | null;
            vex_justification: components["schemas"]["VexJustification"] | null;
            advisory: components["schemas"]["AdvisoryOut"];
            /** Risk Breakdown */
            risk_breakdown: {
                [key: string]: unknown;
            };
            exploitation: components["schemas"]["ExploitationOut"];
            analysis: components["schemas"]["AnalysisOut"] | null;
            /** Symbols */
            symbols: components["schemas"]["SymbolOut"][];
            /** Symbol Provenance */
            symbol_provenance: string;
            /** Reviews */
            reviews: components["schemas"]["ReviewOut"][];
            /** Timeline */
            timeline: components["schemas"]["AuditEventOut"][];
            /** Vex Preview */
            vex_preview: {
                [key: string]: unknown;
            };
            /** Can Review */
            can_review: boolean;
        };
        /** FindingItemOut */
        FindingItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Advisory Id */
            advisory_id: string;
            /** Aliases */
            aliases: string[];
            /** Summary */
            summary: string | null;
            /** Package */
            package: string;
            /** Installed Version */
            installed_version: string | null;
            severity: components["schemas"]["Severity"];
            /** Cvss Score */
            cvss_score: string | null;
            verdict: components["schemas"]["Verdict"] | null;
            effective_verdict: components["schemas"]["Verdict"] | null;
            confidence: components["schemas"]["Confidence"] | null;
            review_state: components["schemas"]["ReviewState"];
            /** Risk Score */
            risk_score: string | null;
            /** Kev */
            kev: boolean;
            /** Epss Percentile */
            epss_percentile: string | null;
            presence: components["schemas"]["Presence"];
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Repository Full Name */
            repository_full_name: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
        };
        /** FindingPage */
        FindingPage: {
            /** Items */
            items: components["schemas"]["FindingItemOut"][];
            /** Total */
            total: number;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Liveness */
        Liveness: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** ManifestOut */
        ManifestOut: {
            /** Path */
            path: string;
            /** Format */
            format: string;
            /** Status */
            status: string;
            /** Detail */
            detail: string | null;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"] | null;
            /** Organizations */
            organizations: components["schemas"]["OrganizationOut"][];
            /** Github Login Enabled */
            github_login_enabled: boolean;
            /** Github Install Url */
            github_install_url: string | null;
        };
        /** OrganizationOut */
        OrganizationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Login */
            login: string;
            /** Account Type */
            account_type: string;
            role: components["schemas"]["Role"];
        };
        /** OverviewOut */
        OverviewOut: {
            organization: components["schemas"]["OrganizationOut"];
            totals: components["schemas"]["VerdictCounts"];
            /** Severity */
            severity: components["schemas"]["SeverityBreakdown"][];
            /** Kev Findings */
            kev_findings: components["schemas"]["FindingItemOut"][];
            /** Top Findings */
            top_findings: components["schemas"]["FindingItemOut"][];
            /** Repositories */
            repositories: components["schemas"]["RepositoryOut"][];
            /** Activity */
            activity: components["schemas"]["AuditEventOut"][];
        };
        /** PathOut */
        PathOut: {
            /** Rank */
            rank: number;
            /** Entrypoint Kind */
            entrypoint_kind: string;
            /** Steps */
            steps: {
                [key: string]: unknown;
            }[];
        };
        /** PolicyIn */
        PolicyIn: {
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
        };
        /** PolicyOut */
        PolicyOut: {
            /** Version */
            version: number;
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** History */
            history: {
                [key: string]: unknown;
            }[];
            /** Can Edit */
            can_edit: boolean;
        };
        /**
         * Presence
         * @enum {string}
         */
        Presence: "present" | "resolved";
        /** PullRequestCheckOut */
        PullRequestCheckOut: {
            /** Pr Number */
            pr_number: number;
            /** Head Sha */
            head_sha: string;
            /** Conclusion */
            conclusion: string | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Readiness */
        Readiness: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failing";
            /** Checks */
            checks: {
                [key: string]: "ok" | "failing";
            };
        };
        /** RepositoryOut */
        RepositoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Source */
            source: string;
            /** Default Branch */
            default_branch: string;
            /** Is Private */
            is_private: boolean;
            latest_scan: components["schemas"]["ScanOut"] | null;
            counts: components["schemas"]["VerdictCounts"];
            /**
             * Health
             * @enum {string}
             */
            health: "healthy" | "attention" | "failing" | "pending";
        };
        /** ReviewIn */
        ReviewIn: {
            /** Expected Version */
            expected_version: number;
            decided_verdict: components["schemas"]["Verdict"];
            vex_status: components["schemas"]["VexStatus"];
            justification?: components["schemas"]["VexJustification"] | null;
            /** Comment */
            comment?: string | null;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reviewer Login */
            reviewer_login: string;
            previous_verdict: components["schemas"]["Verdict"] | null;
            decided_verdict: components["schemas"]["Verdict"];
            vex_status: components["schemas"]["VexStatus"];
            justification: components["schemas"]["VexJustification"] | null;
            /** Comment */
            comment: string | null;
            /** Analysis Result Id */
            analysis_result_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ReviewState
         * @enum {string}
         */
        ReviewState: "unreviewed" | "accepted" | "overridden" | "stale";
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "admin" | "member" | "viewer";
        /** ScanDetailOut */
        ScanDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Commit Sha */
            commit_sha: string;
            /** Ref */
            ref: string | null;
            trigger: components["schemas"]["ScanTrigger"];
            status: components["schemas"]["ScanStatus"];
            /** Stage */
            stage: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Stages */
            stages: string[];
            /** Repository Full Name */
            repository_full_name: string;
            /** Sbom Available */
            sbom_available: boolean;
            /** Manifests */
            manifests: components["schemas"]["ManifestOut"][];
        };
        /** ScanOut */
        ScanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Commit Sha */
            commit_sha: string;
            /** Ref */
            ref: string | null;
            trigger: components["schemas"]["ScanTrigger"];
            status: components["schemas"]["ScanStatus"];
            /** Stage */
            stage: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * ScanStatus
         * @enum {string}
         */
        ScanStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * ScanTrigger
         * @enum {string}
         */
        ScanTrigger: "manual" | "push" | "pull_request" | "advisory" | "schedule" | "demo";
        /** SearchOut */
        SearchOut: {
            /** Repositories */
            repositories: components["schemas"]["RepositoryOut"][];
            /** Findings */
            findings: components["schemas"]["FindingItemOut"][];
            /** Packages */
            packages: {
                [key: string]: unknown;
            }[];
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low" | "unknown";
        /** SeverityBreakdown */
        SeverityBreakdown: {
            severity: components["schemas"]["Severity"];
            /** Reachable */
            reachable: number;
            /** Needs Review */
            needs_review: number;
            /** Not Reached */
            not_reached: number;
        };
        /** SourceHealthOut */
        SourceHealthOut: {
            /** Source */
            source: string;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Status */
            last_status: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Records Seen */
            records_seen: number | null;
            /** Unresolved Failures */
            unresolved_failures: number;
            /** Stale */
            stale: boolean;
        };
        /**
         * SymbolKind
         * @enum {string}
         */
        SymbolKind: "function" | "method" | "class" | "module";
        /**
         * SymbolOrigin
         * @enum {string}
         */
        SymbolOrigin: "advisory" | "ai" | "curated" | "reviewer";
        /** SymbolOut */
        SymbolOut: {
            /** Qualified Name */
            qualified_name: string;
            kind: components["schemas"]["SymbolKind"];
            origin: components["schemas"]["SymbolOrigin"];
            verification: components["schemas"]["SymbolVerification"];
            /** Verification Detail */
            verification_detail: {
                [key: string]: unknown;
            };
            ai_extraction: components["schemas"]["AIExtractionOut"] | null;
        };
        /**
         * SymbolVerification
         * @enum {string}
         */
        SymbolVerification: "verified" | "rejected" | "unverified";
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Login */
            login: string;
            /** Name */
            name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "reachable" | "not_reached" | "needs_review";
        /** VerdictCounts */
        VerdictCounts: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Reachable
             * @default 0
             */
            reachable: number;
            /**
             * Needs Review
             * @default 0
             */
            needs_review: number;
            /**
             * Not Reached
             * @default 0
             */
            not_reached: number;
            /**
             * Pending
             * @default 0
             */
            pending: number;
            /**
             * Kev
             * @default 0
             */
            kev: number;
        };
        /** VexDocumentOut */
        VexDocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            format: components["schemas"]["VexFormat"];
            /** Repository Id */
            repository_id: string | null;
            /** Repository Full Name */
            repository_full_name: string | null;
            /** Statement Count */
            statement_count: number;
            /** Sha256 */
            sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * VexFormat
         * @enum {string}
         */
        VexFormat: "openvex" | "cyclonedx";
        /** VexIn */
        VexIn: {
            format: components["schemas"]["VexFormat"];
        };
        /**
         * VexJustification
         * @description OpenVEX justification values for ``not_affected`` statements.
         * @enum {string}
         */
        VexJustification: "component_not_present" | "vulnerable_code_not_present" | "vulnerable_code_not_in_execute_path" | "vulnerable_code_cannot_be_controlled_by_adversary" | "inline_mitigations_already_exist";
        /**
         * VexStatus
         * @enum {string}
         */
        VexStatus: "not_affected" | "affected" | "fixed" | "under_investigation";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    login_api_v1_auth_github_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_api_v1_auth_github_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    overview_api_v1_orgs__login__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repositories_api_v1_orgs__login__repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_v1_orgs__login__findings_get: {
        parameters: {
            query?: {
                verdict?: components["schemas"]["Verdict"][] | null;
                severity?: components["schemas"]["Severity"][] | null;
                kev?: boolean | null;
                package?: string | null;
                repository_id?: string | null;
                q?: string | null;
                presence?: components["schemas"]["Presence"];
                sort?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_api_v1_orgs__login__activity_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vex_documents_api_v1_orgs__login__vex_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VexDocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_api_v1_orgs__login__policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_policy_api_v1_orgs__login__policy_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_orgs__login__search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path: {
                login: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repository_api_v1_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scans_api_v1_repositories__repository_id__scans_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_api_v1_repositories__repository_id__scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_requests_api_v1_repositories__repository_id__pull_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestCheckOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vex_preview_api_v1_repositories__repository_id__vex_preview_get: {
        parameters: {
            query?: {
                format?: components["schemas"]["VexFormat"];
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vex_api_v1_repositories__repository_id__vex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VexIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VexDocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_detail_api_v1_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_api_v1_scans__scan_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sbom_api_v1_scans__scan_id__sbom_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_finding_api_v1_findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_v1_findings__finding_id__reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_api_v1_demo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoOut"];
                };
            };
        };
    };
    run_demo_scan_api_v1_demo_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoScanOut"];
                };
            };
        };
    };
    advisory_health_api_v1_advisories_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealthOut"][];
                };
            };
        };
    };
    download_vex_api_v1_vex__document_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_webhook_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
