"""finding review summary

Revision ID: e0f8dba12a78
Revises: 417e64dff531
Create Date: 2026-10-06 10:11:39.073178+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e0f8dba12a78"
down_revision: str | None = "417e64dff531"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "findings",
        sa.Column(
            "decided_verdict",
            sa.Enum(
                "reachable",
                "not_reached",
                "needs_review",
                name="decided_verdict",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "findings",
        sa.Column(
            "vex_status",
            sa.Enum(
                "not_affected",
                "affected",
                "fixed",
                "under_investigation",
                name="vex_status",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "findings",
        sa.Column(
            "vex_justification",
            sa.Enum(
                "component_not_present",
                "vulnerable_code_not_present",
                "vulnerable_code_not_in_execute_path",
                "vulnerable_code_cannot_be_controlled_by_adversary",
                "inline_mitigations_already_exist",
                name="vex_justification",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
    # Hand-written: autogenerate does not compare CHECK constraints.
    op.create_check_constraint(
        "ck_findings_decided_verdict",
        "findings",
        "decided_verdict IN ('reachable', 'not_reached', 'needs_review')",
    )
    op.create_check_constraint(
        "ck_findings_vex_status",
        "findings",
        "vex_status IN ('not_affected', 'affected', 'fixed', 'under_investigation')",
    )
    op.create_check_constraint(
        "ck_findings_vex_justification",
        "findings",
        "vex_justification IN ('component_not_present', 'vulnerable_code_not_present', "
        "'vulnerable_code_not_in_execute_path', 'vulnerable_code_cannot_be_controlled_by_adversary', "
        "'inline_mitigations_already_exist')",
    )


def downgrade() -> None:
    for name in (
        "ck_findings_vex_justification",
        "ck_findings_vex_status",
        "ck_findings_decided_verdict",
    ):
        op.drop_constraint(name, "findings", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("findings", "vex_justification")
    op.drop_column("findings", "vex_status")
    op.drop_column("findings", "decided_verdict")
    # ### end Alembic commands ###
