"""initial schema

Revision ID: 417e64dff531
Revises:
Create Date: 2026-10-06 08:22:04.133709+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "417e64dff531"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPEND_ONLY_TABLES = ("audit_events", "review_decisions")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advisories",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=False),
        sa.Column(
            "aliases", postgresql.ARRAY(sa.String(length=128)), server_default="{}", nullable=False
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "critical", "high", "medium", "low", "unknown", name="severity", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("cvss_vector", sa.String(length=256), nullable=True),
        sa.Column("cvss_score", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column(
            "references",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low', 'unknown')",
            name=op.f("ck_advisories_severity"),
        ),
        sa.CheckConstraint(
            "cvss_score >= 0 AND cvss_score <= 10", name=op.f("ck_advisories_cvss_score_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisories")),
        sa.UniqueConstraint("source", "source_id", name=op.f("uq_advisories_source_source_id")),
    )
    op.create_index(
        "ix_advisories_aliases", "advisories", ["aliases"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_advisories_modified_at", "advisories", ["modified_at"], unique=False)
    op.create_table(
        "epss_scores",
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("percentile", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("score_date", sa.Date(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "percentile >= 0 AND percentile <= 1", name=op.f("ck_epss_scores_percentile_range")
        ),
        sa.CheckConstraint("score >= 0 AND score <= 1", name=op.f("ck_epss_scores_score_range")),
        sa.PrimaryKeyConstraint("cve_id", name=op.f("pk_epss_scores")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "succeeded", "partial", "failed", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_seen", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_changed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cursor", sa.String(length=255), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'partial', 'failed')",
            name=op.f("ck_ingestion_runs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        "ix_ingestion_runs_source_started_at",
        "ingestion_runs",
        ["source", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "kev_entries",
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("date_added", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("known_ransomware_use", sa.Boolean(), nullable=False),
        sa.Column("vendor", sa.String(length=255), nullable=False),
        sa.Column("product", sa.String(length=255), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("cve_id", name=op.f("pk_kev_entries")),
    )
    op.create_table(
        "organizations",
        sa.Column("github_account_id", sa.BigInteger(), nullable=True),
        sa.Column("login", sa.String(length=100), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum("user", "organization", "demo", name="account_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_type IN ('user', 'organization', 'demo')",
            name=op.f("ck_organizations_account_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("github_account_id", name=op.f("uq_organizations_github_account_id")),
    )
    op.create_table(
        "packages",
        sa.Column("ecosystem", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
        sa.UniqueConstraint("ecosystem", "name", name=op.f("uq_packages_ecosystem_name")),
    )
    op.create_table(
        "users",
        sa.Column("github_user_id", sa.BigInteger(), nullable=False),
        sa.Column("login", sa.String(length=39), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("github_user_id", name=op.f("uq_users_github_user_id")),
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("github_delivery_id", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=True),
        sa.Column("github_installation_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("github_delivery_id", name=op.f("pk_webhook_deliveries")),
    )
    op.create_table(
        "advisory_packages",
        sa.Column("advisory_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column(
            "ranges", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "versions", postgresql.ARRAY(sa.String(length=128)), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisories.id"],
            name=op.f("fk_advisory_packages_advisory_id_advisories"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_advisory_packages_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advisory_packages")),
        sa.UniqueConstraint(
            "advisory_id", "package_id", name=op.f("uq_advisory_packages_advisory_id_package_id")
        ),
    )
    op.create_index(
        op.f("ix_advisory_packages_package_id"), "advisory_packages", ["package_id"], unique=False
    )
    op.create_table(
        "ai_extractions",
        sa.Column("advisory_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("input_sha256", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "succeeded",
                "schema_invalid",
                "provider_error",
                "refused",
                name="status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'schema_invalid', 'provider_error', 'refused')",
            name=op.f("ck_ai_extractions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisories.id"],
            name=op.f("fk_ai_extractions_advisory_id_advisories"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_ai_extractions_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_extractions")),
    )
    op.create_index(
        "ix_ai_extractions_advisory_id_package_id",
        "ai_extractions",
        ["advisory_id", "package_id"],
        unique=False,
    )
    op.create_index(
        "uq_ai_extractions_cache_key",
        "ai_extractions",
        ["input_sha256", "provider", "model", "prompt_version"],
        unique=True,
        postgresql_where=sa.text("status = 'succeeded'"),
    )
    op.create_table(
        "audit_events",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "actor_type",
            sa.Enum("user", "system", "github", name="actor_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prev_hash", sa.LargeBinary(length=32), nullable=True),
        sa.Column("hash", sa.LargeBinary(length=32), nullable=False),
        sa.CheckConstraint(
            "actor_type IN ('user', 'system', 'github')", name=op.f("ck_audit_events_actor_type")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("id", name=op.f("uq_audit_events_id")),
    )
    op.create_index(
        "ix_audit_events_organization_id_seq",
        "audit_events",
        ["organization_id", "seq"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_target", "audit_events", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "github_installations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("github_installation_id", sa.BigInteger(), nullable=False),
        sa.Column("account_login", sa.String(length=100), nullable=False),
        sa.Column("repository_selection", sa.String(length=16), nullable=False),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "repository_selection IN ('all', 'selected')",
            name=op.f("ck_github_installations_repository_selection"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_github_installations_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_installations")),
        sa.UniqueConstraint(
            "github_installation_id", name=op.f("uq_github_installations_github_installation_id")
        ),
    )
    op.create_index(
        op.f("ix_github_installations_organization_id"),
        "github_installations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "ingestion_failures",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("record_id", sa.String(length=255), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("payload_excerpt", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_ingestion_failures_run_id_ingestion_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_failures")),
    )
    op.create_index(
        op.f("ix_ingestion_failures_run_id"), "ingestion_failures", ["run_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "succeeded", "dead", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column("priority", sa.SmallInteger(), server_default="100", nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'dead')", name=op.f("ck_jobs_status")
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= max_attempts", name=op.f("ck_jobs_attempts_bounded")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index(
        "ix_jobs_claimable",
        "jobs",
        ["priority", "run_after"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_jobs_dead",
        "jobs",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'dead'"),
    )
    op.create_index(
        "ix_jobs_leases",
        "jobs",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "memberships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "member", "viewer", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member', 'viewer')", name=op.f("ck_memberships_role")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("organization_id", "user_id", name=op.f("pk_memberships")),
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "policies",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_policies_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policies")),
        sa.UniqueConstraint(
            "organization_id", "name", name=op.f("uq_policies_organization_id_name")
        ),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "policy_versions",
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_policy_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"], ["policies.id"], name=op.f("fk_policy_versions_policy_id_policies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_versions")),
        sa.UniqueConstraint(
            "policy_id", "version", name=op.f("uq_policy_versions_policy_id_version")
        ),
    )
    op.create_table(
        "repositories",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("installation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source", sa.Enum("github", "demo", name="source", native_enum=False), nullable=False
        ),
        sa.Column("github_repo_id", sa.BigInteger(), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("is_private", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("latest_scan_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'demo') = (installation_id IS NULL)",
            name=op.f("ck_repositories_source_matches_installation"),
        ),
        sa.CheckConstraint("source IN ('github', 'demo')", name=op.f("ck_repositories_source")),
        sa.ForeignKeyConstraint(
            ["installation_id"],
            ["github_installations.id"],
            name=op.f("fk_repositories_installation_id_github_installations"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_repositories_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("github_repo_id", name=op.f("uq_repositories_github_repo_id")),
        sa.UniqueConstraint(
            "organization_id", "full_name", name=op.f("uq_repositories_organization_id_full_name")
        ),
    )
    op.create_index(
        op.f("ix_repositories_installation_id"), "repositories", ["installation_id"], unique=False
    )
    op.create_table(
        "vulnerable_symbols",
        sa.Column("advisory_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("qualified_name", sa.String(length=512), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("function", "method", "class", "module", name="kind", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum("advisory", "ai", "curated", "reviewer", name="origin", native_enum=False),
            nullable=False,
        ),
        sa.Column("ai_extraction_id", sa.Uuid(), nullable=True),
        sa.Column(
            "verification",
            sa.Enum("verified", "rejected", "unverified", name="verification", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "verification_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(origin = 'ai') = (ai_extraction_id IS NOT NULL)",
            name=op.f("ck_vulnerable_symbols_ai_origin_has_extraction"),
        ),
        sa.CheckConstraint(
            "kind IN ('function', 'method', 'class', 'module')",
            name=op.f("ck_vulnerable_symbols_kind"),
        ),
        sa.CheckConstraint(
            "origin IN ('advisory', 'ai', 'curated', 'reviewer')",
            name=op.f("ck_vulnerable_symbols_origin"),
        ),
        sa.CheckConstraint(
            "verification IN ('verified', 'rejected', 'unverified')",
            name=op.f("ck_vulnerable_symbols_verification"),
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"],
            ["advisories.id"],
            name=op.f("fk_vulnerable_symbols_advisory_id_advisories"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_extraction_id"],
            ["ai_extractions.id"],
            name=op.f("fk_vulnerable_symbols_ai_extraction_id_ai_extractions"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_vulnerable_symbols_package_id_packages")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vulnerable_symbols")),
        sa.UniqueConstraint(
            "advisory_id",
            "package_id",
            "qualified_name",
            name=op.f("uq_vulnerable_symbols_advisory_id_package_id_qualified_name"),
        ),
    )
    op.create_table(
        "scans",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("ref", sa.String(length=255), nullable=True),
        sa.Column(
            "trigger",
            sa.Enum(
                "manual",
                "push",
                "pull_request",
                "advisory",
                "schedule",
                "demo",
                name="trigger",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column(
            "progress", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("analyzer_version", sa.String(length=32), nullable=False),
        sa.Column("sbom_key", sa.String(length=512), nullable=True),
        sa.Column("sbom_sha256", sa.LargeBinary(length=32), nullable=True),
        sa.Column(
            "stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("commit_sha ~ '^[0-9a-f]{40}$'", name=op.f("ck_scans_commit_sha_hex")),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_scans_status"),
        ),
        sa.CheckConstraint(
            "trigger IN ('manual', 'push', 'pull_request', 'advisory', 'schedule', 'demo')",
            name=op.f("ck_scans_trigger"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_scans_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("fk_scans_repository_id_repositories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_scans_idempotency_key")),
    )
    op.create_index(
        "ix_scans_active",
        "scans",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "ix_scans_repository_id_created_at",
        "scans",
        ["repository_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "vex_documents",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=True),
        sa.Column(
            "format",
            sa.Enum("openvex", "cyclonedx", name="format", native_enum=False),
            nullable=False,
        ),
        sa.Column("artifact_key", sa.String(length=512), nullable=False),
        sa.Column("artifact_sha256", sa.LargeBinary(length=32), nullable=False),
        sa.Column("statement_count", sa.Integer(), nullable=False),
        sa.Column("schema_valid", sa.Boolean(), nullable=False),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('openvex', 'cyclonedx')", name=op.f("ck_vex_documents_format")
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name=op.f("fk_vex_documents_generated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vex_documents_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_vex_documents_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vex_documents")),
    )
    op.create_index(
        op.f("ix_vex_documents_organization_id"), "vex_documents", ["organization_id"], unique=False
    )
    op.create_table(
        "dependencies",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=128), nullable=True),
        sa.Column("constraint_spec", sa.String(length=512), nullable=True),
        sa.Column("is_direct", sa.Boolean(), nullable=False),
        sa.Column("manifest_path", sa.String(length=1024), nullable=False),
        sa.Column("purl", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_dependencies_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_dependencies_scan_id_scans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dependencies")),
        sa.UniqueConstraint(
            "scan_id",
            "package_id",
            "version",
            name=op.f("uq_dependencies_scan_id_package_id_version"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_dependencies_package_id"), "dependencies", ["package_id"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("advisory_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("installed_version", sa.String(length=128), nullable=True),
        sa.Column("first_seen_scan_id", sa.Uuid(), nullable=False),
        sa.Column("last_seen_scan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "presence",
            sa.Enum("present", "resolved", name="presence", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "analysis_state",
            sa.Enum(
                "pending",
                "analyzing",
                "analyzed",
                "failed",
                name="analysis_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "verdict",
            sa.Enum("reachable", "not_reached", "needs_review", name="verdict", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "confidence",
            sa.Enum("high", "medium", "low", name="confidence", native_enum=False),
            nullable=True,
        ),
        sa.Column("latest_analysis_id", sa.Uuid(), nullable=True),
        sa.Column("risk_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "risk_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "review_state",
            sa.Enum(
                "unreviewed",
                "accepted",
                "overridden",
                "stale",
                name="review_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "analysis_state <> 'analyzed' OR verdict IS NOT NULL",
            name=op.f("ck_findings_analyzed_has_verdict"),
        ),
        sa.CheckConstraint(
            "analysis_state IN ('pending', 'analyzing', 'analyzed', 'failed')",
            name=op.f("ck_findings_analysis_state"),
        ),
        sa.CheckConstraint(
            "confidence IN ('high', 'medium', 'low')", name=op.f("ck_findings_confidence")
        ),
        sa.CheckConstraint(
            "presence IN ('present', 'resolved')", name=op.f("ck_findings_presence")
        ),
        sa.CheckConstraint(
            "review_state IN ('unreviewed', 'accepted', 'overridden', 'stale')",
            name=op.f("ck_findings_review_state"),
        ),
        sa.CheckConstraint(
            "verdict IN ('reachable', 'not_reached', 'needs_review')",
            name=op.f("ck_findings_verdict"),
        ),
        sa.CheckConstraint(
            "(verdict IS NULL) = (confidence IS NULL)",
            name=op.f("ck_findings_verdict_has_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["advisory_id"], ["advisories.id"], name=op.f("fk_findings_advisory_id_advisories")
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_scan_id"], ["scans.id"], name=op.f("fk_findings_first_seen_scan_id_scans")
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_scan_id"], ["scans.id"], name=op.f("fk_findings_last_seen_scan_id_scans")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_findings_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["package_id"], ["packages.id"], name=op.f("fk_findings_package_id_packages")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_findings_repository_id_repositories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint(
            "repository_id",
            "advisory_id",
            "package_id",
            name=op.f("uq_findings_repository_id_advisory_id_package_id"),
        ),
    )
    op.create_index(
        "ix_findings_org_verdict_risk",
        "findings",
        ["organization_id", "verdict", sa.literal_column("risk_score DESC")],
        unique=False,
    )
    op.create_index(
        "ix_findings_repository_id_presence",
        "findings",
        ["repository_id", "presence"],
        unique=False,
    )
    op.create_table(
        "pull_request_checks",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column("base_sha", sa.String(length=40), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=True),
        sa.Column("policy_version_id", sa.Uuid(), nullable=True),
        sa.Column("github_check_run_id", sa.BigInteger(), nullable=True),
        sa.Column("conclusion", sa.String(length=32), nullable=True),
        sa.Column(
            "summary", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_pull_request_checks_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"],
            ["policy_versions.id"],
            name=op.f("fk_pull_request_checks_policy_version_id_policy_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_pull_request_checks_repository_id_repositories"),
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_pull_request_checks_scan_id_scans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pull_request_checks")),
        sa.UniqueConstraint(
            "repository_id", "head_sha", name=op.f("uq_pull_request_checks_repository_id_head_sha")
        ),
    )
    op.create_table(
        "scan_manifests",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum("parsed", "unsupported", "error", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('parsed', 'unsupported', 'error')", name=op.f("ck_scan_manifests_status")
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_scan_manifests_scan_id_scans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_manifests")),
        sa.UniqueConstraint("scan_id", "path", name=op.f("uq_scan_manifests_scan_id_path")),
    )
    op.create_table(
        "analysis_results",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("analyzer_version", sa.String(length=32), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("reachable", "not_reached", "needs_review", name="verdict", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("high", "medium", "low", name="confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "reasons", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "symbols", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IN ('high', 'medium', 'low')", name=op.f("ck_analysis_results_confidence")
        ),
        sa.CheckConstraint(
            "verdict IN ('reachable', 'not_reached', 'needs_review')",
            name=op.f("ck_analysis_results_verdict"),
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"], ["findings.id"], name=op.f("fk_analysis_results_finding_id_findings")
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_analysis_results_scan_id_scans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_results")),
    )
    op.create_index(
        "ix_analysis_results_finding_id_created_at",
        "analysis_results",
        ["finding_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "reachability_paths",
        sa.Column("analysis_result_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("entrypoint_kind", sa.String(length=32), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_results.id"],
            name=op.f("fk_reachability_paths_analysis_result_id_analysis_results"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reachability_paths")),
        sa.UniqueConstraint(
            "analysis_result_id", "rank", name=op.f("uq_reachability_paths_analysis_result_id_rank")
        ),
    )
    op.create_table(
        "review_decisions",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_result_id", sa.Uuid(), nullable=True),
        sa.Column("finding_version", sa.Integer(), nullable=False),
        sa.Column(
            "previous_verdict",
            sa.Enum(
                "reachable",
                "not_reached",
                "needs_review",
                name="previous_verdict",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "decided_verdict",
            sa.Enum(
                "reachable",
                "not_reached",
                "needs_review",
                name="decided_verdict",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "vex_status",
            sa.Enum(
                "not_affected",
                "affected",
                "fixed",
                "under_investigation",
                name="vex_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "justification",
            sa.Enum(
                "component_not_present",
                "vulnerable_code_not_present",
                "vulnerable_code_not_in_execute_path",
                "vulnerable_code_cannot_be_controlled_by_adversary",
                "inline_mitigations_already_exist",
                name="justification",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decided_verdict IN ('reachable', 'not_reached', 'needs_review')",
            name=op.f("ck_review_decisions_decided_verdict"),
        ),
        sa.CheckConstraint(
            "justification IN ('component_not_present', 'vulnerable_code_not_present', 'vulnerable_code_not_in_execute_path', 'vulnerable_code_cannot_be_controlled_by_adversary', 'inline_mitigations_already_exist')",
            name=op.f("ck_review_decisions_justification"),
        ),
        sa.CheckConstraint(
            "previous_verdict IN ('reachable', 'not_reached', 'needs_review')",
            name=op.f("ck_review_decisions_previous_verdict"),
        ),
        sa.CheckConstraint(
            "vex_status <> 'not_affected' OR justification IS NOT NULL",
            name=op.f("ck_review_decisions_not_affected_requires_justification"),
        ),
        sa.CheckConstraint(
            "vex_status IN ('not_affected', 'affected', 'fixed', 'under_investigation')",
            name=op.f("ck_review_decisions_vex_status"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"],
            ["analysis_results.id"],
            name=op.f("fk_review_decisions_analysis_result_id_analysis_results"),
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"], ["findings.id"], name=op.f("fk_review_decisions_finding_id_findings")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_review_decisions_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_review_decisions_reviewer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
    )
    op.create_index(
        "ix_review_decisions_finding_id_created_at",
        "review_decisions",
        ["finding_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Hand-written: foreign keys that close a cycle (repositories <-> scans,
    # findings <-> analysis_results) can only be added once both tables exist.
    op.create_foreign_key(
        op.f("fk_repositories_latest_scan_id_scans"),
        "repositories",
        "scans",
        ["latest_scan_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_findings_latest_analysis_id_analysis_results"),
        "findings",
        "analysis_results",
        ["latest_analysis_id"],
        ["id"],
    )

    # Hand-written: append-only enforcement at the storage layer (docs/database.md).
    op.execute(
        """
        CREATE FUNCTION reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only', TG_TABLE_NAME
                USING ERRCODE = 'insufficient_privilege';
        END
        $$
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_mutation()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation()"
        )


def downgrade() -> None:
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    op.execute("DROP FUNCTION reject_mutation()")
    op.drop_constraint(
        op.f("fk_findings_latest_analysis_id_analysis_results"), "findings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_repositories_latest_scan_id_scans"), "repositories", type_="foreignkey"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_decisions_finding_id_created_at", table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_table("reachability_paths")
    op.drop_index("ix_analysis_results_finding_id_created_at", table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_table("scan_manifests")
    op.drop_table("pull_request_checks")
    op.drop_index("ix_findings_repository_id_presence", table_name="findings")
    op.drop_index("ix_findings_org_verdict_risk", table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_dependencies_package_id"), table_name="dependencies")
    op.drop_table("dependencies")
    op.drop_index(op.f("ix_vex_documents_organization_id"), table_name="vex_documents")
    op.drop_table("vex_documents")
    op.drop_index("ix_scans_repository_id_created_at", table_name="scans")
    op.drop_index(
        "ix_scans_active",
        table_name="scans",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_table("scans")
    op.drop_table("vulnerable_symbols")
    op.drop_index(op.f("ix_repositories_installation_id"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("policies")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(
        "ix_jobs_leases", table_name="jobs", postgresql_where=sa.text("status = 'running'")
    )
    op.drop_index("ix_jobs_dead", table_name="jobs", postgresql_where=sa.text("status = 'dead'"))
    op.drop_index(
        "ix_jobs_claimable", table_name="jobs", postgresql_where=sa.text("status = 'pending'")
    )
    op.drop_table("jobs")
    op.drop_index(op.f("ix_ingestion_failures_run_id"), table_name="ingestion_failures")
    op.drop_table("ingestion_failures")
    op.drop_index(
        op.f("ix_github_installations_organization_id"), table_name="github_installations"
    )
    op.drop_table("github_installations")
    op.drop_index("ix_audit_events_target", table_name="audit_events")
    op.drop_index("ix_audit_events_organization_id_seq", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(
        "uq_ai_extractions_cache_key",
        table_name="ai_extractions",
        postgresql_where=sa.text("status = 'succeeded'"),
    )
    op.drop_index("ix_ai_extractions_advisory_id_package_id", table_name="ai_extractions")
    op.drop_table("ai_extractions")
    op.drop_index(op.f("ix_advisory_packages_package_id"), table_name="advisory_packages")
    op.drop_table("advisory_packages")
    op.drop_table("webhook_deliveries")
    op.drop_table("users")
    op.drop_table("packages")
    op.drop_table("organizations")
    op.drop_table("kev_entries")
    op.drop_index("ix_ingestion_runs_source_started_at", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_table("epss_scores")
    op.drop_index("ix_advisories_modified_at", table_name="advisories")
    op.drop_index("ix_advisories_aliases", table_name="advisories", postgresql_using="gin")
    op.drop_table("advisories")
    # ### end Alembic commands ###
